### ISSUE TITLE
Improve the documentation of makeup combinators

### ISSUE THREAD

**Issue by tmbb** [tmbb/makeup#10]
There are two places where we can add this documentation:

* The `@doc` attributes of the function themselves
* The CONTRIBUTING.md file

These different places might call for different styles of documentation.

**Comment by tmbb** [comment]
This has been much improved but could be improved even more, this issue will continue open for some time.

**Comment by kianmeng** [comment]
@tmbb Is this still relevant today? Are there anything else needed?
