### ISSUE TITLE
Registry API

### ISSUE THREAD

**Issue by tmbb** [tmbb/makeup#13]
Makeup should support a global registry in which lexers can register themselves on application start.

That way a new lexer can be made available from a language name just by declaring it as a dependency.

**Comment by tmbb** [comment]
Motivation here: https://github.com/elixir-lang/ex_doc/pull/853#issuecomment-390621535

**Comment by tmbb** [comment]
Pinging @josevalim because he was the one to suggest this in an ExDoc issue.

The API I have is very simple. Makeup now executes code on application start, which creates a lexer registry where you can register lexers by name.

Lexers can make use of it by registering themselves on application start. For example, the code I've written for the Elixir lexer:

```elixir
defmodule Makeup.Lexers.ElixirLexer.Application do
  @moduledoc false
  use Application

  alias Makeup.Registry
  alias Makeup.Lexers.ElixirLexer

  def start(_type, _args) do
    Registry.register_lexer_with_name("elixir", {ElixirLexer, []})
    # Use the normal Elixir lexer for `iex` prompts
    Registry.register_lexer_with_name("iex", {ElixirLexer, []})
    Supervisor.start_link([], strategy: :one_for_one)
  end
end
```

This could be made even more concise with something like:

```elixir
defmodule Makeup.Lexers.ElixirLexer.Application do
  use Makeup.Registry, lexer: Makeup.Lexers.ElixirLexer, names: ["elixir", "iex"]
end
```

but that seems needlessly obscure.

Should I add an extension registry, so that the Elixir lexer could be associated with the `.ex` and `.exs` extensions, for example?

**Comment by josevalim** [comment]
It looks great.

> Should I add an extension registry, so that the Elixir lexer could be associated with the .ex and .exs extensions, for example?

Yes. Probably the same registry is fine, just another field. :+1:

**Comment by tmbb** [comment]
Done since version 0.8
