### ISSUE TITLE
Rename release alias to avoid collision with elixir 1.9 mix release

### ISSUE THREAD

**Issue by mracos** [tmbb/makeup#26]
With the `release` mix command [introduced in `Elixir 1.9`](https://github.com/elixir-lang/elixir/pull/8677), we should probably change [the command that releases a new version](https://github.com/tmbb/makeup/blob/master/mix.exs#L46) of the lib to something like `publish` (?) as to avoid collision with the official mix command and to lessen the possibility of confusion for newcomers. 😄

**Comment by tmbb** [comment]
Yes, I think we should. I had no idea there was a new "release command". But I'm not sure whether `publish` is the best name.

**Comment by antedeguemon** [comment]
@tmbb the issue was fixed by [this commit](https://github.com/elixir-makeup/makeup/commit/c68dc975a41ed7af98915aa018fb68e86146bac9#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308).

**Comment by mracos** [comment]
Tks for the heads up @antedeguemon!
