### ISSUE TITLE
Include lists/ranges of semantically significant unicode characters?

### ISSUE THREAD

**Issue by tmbb** [tmbb/makeup#31]
Currently the Elixir lexer doesn't recognize the full set of valid identifiers, which can contain a lot of unicode characters. It recognizes only ASCII characters. The excelent [unicode_set]() library by @kipcole9 allows us to extract from the unicode database the character ranges we need.

The problem is that `unicode_set` takes *a lot* of time to compile (several minutes on my machine). I don't think these compile times are acceptable for makeup lexers. Fortunately, we can make `unicode_set` a `:dev` dependency to generate an elixir file that contains a module which returns the raw list of characters without having to depend on `unicode_set` at runtime and at compile-time.

Here is the module I generate at *dev-time* (I don't know if this concept exists, but it should): https://github.com/tmbb/makeup_go/blob/master/lib/makeup/lexers/go_lexer/utf8_utils.ex

And here is the code that generates the module: https://github.com/tmbb/makeup_go/blob/master/unicode/generate.exs

I can generate the module with `mix run unicode/generate.exs`.

This approach works and is quite clean. My question is the following: several languages require support for unicode identifiers. Should we add these kinds of modules directly to Makeup? Or should we make that the responsability of lexer writers?

In favour of adding it to makeup:

* It centralizes unicode support and encapsulates the common problem of writing the "module generators"

Against adding it to makeup:

* Different languages will require different unicode character sets. There isn't an obvious set of characters we must support.
* Writing the "module generators" is actually very easy, especially as you can copy-paste parts from the go lexer for example

**Comment by josevalim** [comment]
Elixir does something similar. It reads values directly from Unicode files and generates a bunch of clauses that match on those values. Here is the module that we generate: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/unicode/tokenizer.ex Its APIs are private but the module itself can be used as a foundation. So I would generally prefer an approach that generates the module at compile time, instead of depending on unicode_set at runtime.

**Comment by tmbb** [comment]
> Elixir does something similar.

It's not that similar. I don't generate the character ranges at compile time. That would still require a `:prod` dependency (not only a `:dev` dependency) on `unicode_set`. I have a script that writes a *file* with an elixir module that returns the lists I need. That way the `unicode_set` isn't even needed during compilation.

I would never want to use `unicode_set` at runtime or even at compile time. My question is whether these generated modules should live in the lexers or in `makeup`. Probably the lexers because the identifier rules are so different in different programming languages...

**Comment by josevalim** [comment]
> It's not that similar. I don't generate the character ranges at compile time.

What I was saying is that you could have those ranges in a file. So instead of generating an Elixir module, you could generate a file with the endpoints and then use that to build the module. All without needing unicodeset in prod!

> Probably the lexers because the identifier rules are so different in different programming languages...

Agreed.
