### ISSUE TITLE
makeup_json lexer

### ISSUE THREAD

**Issue by lkarthee** [tmbb/makeup#42]
I have created a lexer for json. It is derived from makeup_elixir. Instead of writing from scratch - i started makeup_elixir as base.

https://github.com/lkarthee/makeup_json

Should the repo be moved to elixir-makeup org? It will be easy for people to discover if it is in this org.

Let me know if you are interested.

**Comment by josevalim** [comment]
Sounds great, thanks for asking, please do transfer the repo! :)

**Comment by josevalim** [comment]
If you can't transfer, add me as admin, then I will transfer and make you a repo admin. :)

**Comment by lkarthee** [comment]
I sent an invite adding you as collaborator.

**Comment by josevalim** [comment]
@lkarthee accepted! please make me an admin and i will transfer it :)

**Comment by lkarthee** [comment]
@josevalim i am unable to find a way to add you as admin (as it is not in an org). So I have transferred it to your handle. 

>  This repository is being transferred to @josevalim.

Please accept it.

**Comment by josevalim** [comment]
Thank you! I have moved it to the org, kept you as an repo admin, and invited you to the org too! :heart:
