### ISSUE TITLE
Is anybody working in a Markdown lexer?

### ISSUE THREAD

**Issue by fabrithedev** [tmbb/makeup#51]
I don't know if this is the right place to ask, please forgive me if it isn't.

I started working on a Markdown lexer for makeup and wanted to know if there is already a project for a Markdown lexer (to avoid duplicate efforts).

My project is still in the early stages and I'm following the [CommonMark specification
](https://spec.commonmark.org/0.30/)

I need some guidance if its the right way to start a new lexer.

Repo: https://github.com/FabriDamazio/makeup_markdown

Current stage: working on lexing ATX Headings 

![image](https://user-images.githubusercontent.com/3181570/182983194-017733c8-3f01-4cf0-ad76-82828a486987.png)

**Comment by josevalim** [comment]
It looks good to me but I have never written one. :) the best way is to check how the Elixir/Erlang levers are written!

**Comment by fabrithedev** [comment]
Ok @josevalim 
I will keep working on it and ill msg you guys when its finished.
