### ISSUE TITLE
Highlighting 'end' differently depending on what it matches

### ISSUE THREAD

**Issue by TheArrowsmith** [tmbb/makeup#54]
I'm trying to write a Ruby lexer for Makeup.

In my Vim setup, the `end` keyword takes a different colour depending on what exactly it's ending:

![image](https://user-images.githubusercontent.com/85154056/195780104-c4c58780-5c78-4938-b43c-108726db0f81.png)

See how the three `end`s in that screenshot have different colours to match the `if`, `def` and `class`.

Is there an easy way to do this in Makeup? I'm looking at the `ElixirLexer` source to see how it might be done - I see there's a `defgroupmatcher` macro but this seems to be used just to add the `data-group-id` tags to each element. Is there some way this can also be used to update the token names so `end` tags (or whatever closing elements really) have the same token type as what they close?

I suppose I could do it by iterating back over the whole list after `defgroupmatcher` has been run and updating the existing tags based on their `data-group-id`s but this feels a bit hacky - is there some obviously better alternative that I'm missing?

**Comment by josevalim** [comment]
This is harder in Elixir because def, if, class are not keywords. In Elixir, they have a matching do/end, so that's what you would highlight.

The other difficulty is that makeup only emits certain classes with specific semantic meaning, so picking up a random color is not easily doable, afaik.

However, there is already some JS for pair-highlighting, and I think you could add a small tiny additional bit of JS too to change the colors of the pairs based on data-group-id and their content/classes.

**Comment by tmbb** [comment]
Look at the tokens the lexers generate for cases such as matching keywords and parentheses. Those tokens contain an extra attribute which identifies the other matching tokens. You can write a custom formatter that uses that information to generate different color per matching group. There's no need for extra JavaScript.

**Comment by josevalim** [comment]
Ah, a custom formatter is even better. Closing then!

**Comment by TheArrowsmith** [comment]
Okay. I was just wondering if there was some obvious existing solution but it sounds like there isn't, so I came up with my own solution that handles this within the lexer rather than deferring it to the formatting step.

If anyone is curious, here's my code that accomplishes this:

```elixir
  defp update_closing_tokens(tokens) do
    update_closing_tokens_helper(tokens, %{})
  end

  defp update_closing_tokens_helper(
    [{token, %{group_id: gid} = attrs, text} | tail],
    tags
  ) do
    {head, new_tags} =
      if Map.has_key?(tags, gid) do
        {{Map.get(tags, gid), attrs, text}, tags}
      else
        {{token, attrs, text}, Map.put(tags, gid, token)}
      end
    [head | update_closing_tokens_helper(tail, new_tags)]
  end

  defp update_closing_tokens_helper([token | tokens], tags) do
    [token | update_closing_tokens_helper(tokens, tags)]
  end

  defp update_closing_tokens_helper([], _), do: []
```

This is for a lexer that follows the same basic pattern as the Elixir lexer; you can stick `|> update_closing_tokens` below `|> match_groups(group_prefix)` [here](https://github.com/elixir-makeup/makeup_elixir/blob/8539ad5adb9054cc51a6fe44a538cff767cf9410/lib/makeup/lexers/elixir_lexer.ex#L621).

The idea is that if your initial pass through lexes the code in my original example to, say:

- "class", `:keyword_namespace`
- …
- "def", `:keyword_declaration`
- …
- "if", `:keyword_reserved`
- …
- "end", `:keyword`
- "end", `:keyword`
- "end", `:keyword`

... then after the `update_closing_tokens` step, the new lexed output will be:

- "class", `:keyword_namespace`
- …
- "def", `:keyword_declaration`
- …
- "if", `:keyword_reserved`
- …
- "end", `:keyword_reserved`
- "end", `:keyword_declaration`
- "end", `:keyword_namespace`
