### ISSUE TITLE
Rust lexer

### ISSUE THREAD

**Issue by dottorblaster** [tmbb/makeup#56]
Hi everybody :wave:

I've been working for some time to a [new lexer that can highlight Rust syntax](https://github.com/dottorblaster/makeup_rust). I thought it would be nice especially considered the growing usage of Rustler in the ecosystem.

Would it be good to move the repo to this organization for easier discoverability? Let me know :-)

**Comment by dottorblaster** [comment]
Ping?

**Comment by tmbb** [comment]
I'm ok with this, if @josevalim is also ok with it we can add your repo.

**Comment by tmbb** [comment]
@dottorblaster I have added you as member to the organization so you should be able to transfer ownership of the repo.

**Comment by dottorblaster** [comment]
@tmbb thank you so much!

**Comment by josevalim** [comment]
Hi @dottorblaster! @SteffenDE has [recently made bindings to Rust's syntect](https://github.com/steffenDE/makeup_syntect). While I believe we should prefer Elixir-centric solutions for BEAM languages, given you are already using Rust, you may be interested in giving it a try too. It should at least offer a more complete highlighting for Rust itself?

**Comment by SteffenDE** [comment]
just fyi: there's a Rust example in the docs: https://hexdocs.pm/makeup_syntect/rust.html - it may be necessary to tweak the mapping of Sublime Text scopes to Makeup tokens per language to further improve the highlighting. Contributions are very welcome!

**Comment by dottorblaster** [comment]
@josevalim @SteffenDE this is _very_ cool, maybe we could also have `makeup_rust` relying on this instead of the default depending on a configuration parameter. Thank you for letting me know!

**Comment by josevalim** [comment]
@dottorblaster in this case, I think we probably wouldn't need `makeup_rust`anymore, as you can use `makeup_syntect`, but that's your decision to make! Please give it a try and let us know how to proceed!

**Comment by dottorblaster** [comment]
@josevalim I can archive `makeup_rust` right away, could you also move `makeup_syntect` to this organization?

**Comment by josevalim** [comment]
We have a discussion for moving the other one here, but feel free to archive it meanwhile.

**Comment by dottorblaster** [comment]
Turns out I don't have the required rights to archive it 😬

**Comment by josevalim** [comment]
Done!
