### ISSUE TITLE
Use with Earmark for syntax coloring?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [tmbb/makeup#58]
Could your provide guidance on how Makeup could be used to provide syntax coloring for Earmark generated html in a LiveView page?

**Comment by CharlesIrvineKC** [comment]
Sorry, I think I had already posted this issue.

**Comment by CharlesIrvineKC** [comment]
Sorry, that post was to a different repo.

**Comment by josevalim** [comment]
See this project and file as an example: https://github.com/dashbitco/nimble_publisher/blob/master/lib/nimble_publisher/highlighter.ex

**Comment by CharlesIrvineKC** [comment]
I now have syntax coloring. It took me awhile though. I didn't know about the requirement to run:
```
Makeup.stylesheet(:colorful_style, "makeup") |> IO.puts()
```
Once I figured that out, it all started working.

Thanks. Thanks. Thanks.

Now if I could just figure out how to bring in math symbols, I'd be set.
